path: C:/Code/Projetinhos/IC-Gemeo-master/IC-Gemeo-master/imagens/ic-basico.v7i.yolov8-obb
#path: C:/Code/IC-Gemeo-Mater/IC-Gemeo-master/imagens/ic-basico.v8i.yolov8-obb
train: ../train/images
val: ../valid/images
test: ../test/images

names:
  0: pecaPreta
